site_name: APIFlask
site_description: A lightweight Python web API framework.
site_url: https://apiflask.com
docs_dir: docs_fa
theme:
  name: material
  custom_dir: docs_fa/_templates
  logo: _assets/white-logo.png
  favicon: _assets/favicon.png
  palette:
    primary: deep orange
  icon:
    repo: fontawesome/brands/github
  language: fa
repo_url: https://github.com/apiflask/apiflask
repo_name: apiflask/apiflask
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/apiflask/apiflask
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/apiflask
  alternate:
    - name: English
      link: https://apiflask.com
      lang: en
    - name: 简体中文
      link: https://zh.apiflask.com
      lang: zh
    - name: فارسی
      link: https://fa.apiflask.com
      lang: fa
copyright:
  Copyright &copy; 2021 <a href="https://github.com/greyli" target="_blank" rel="noopener">Grey Li</a><br>
  <span style="color:#555">Hosted with</span> <a href="https://www.netlify.com" target="_blank" rel="noopener">Netlify</a>
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.progressbar
  - attr_list
  - toc:
      permalink: True
nav:
  - خانه: index.md
  - فهرست مستندات: docs.md
  - مهاجرت از فلاسک: migrating.md
  - استفاده پایه: usage.md
  - مدیریت ریکوئست ها: request.md
  - فرمت کردن پاسخ ها: response.md
  - طرحواره داده ها: schema.md
  - احراز هویت: authentication.md
  - ایجاد OpenAPI: openapi.md
  - مستندات API: api-docs.md
  - پیکربندی: configuration.md
  - مدیریت ارور ها: error-handling.md
  - مثال ها: examples.md
  - مرجع API:
      - APIFlask: api/app.md
      - APIBlueprint: api/blueprint.md
      - Exceptions: api/exceptions.md
      - OpenAPI: api/openapi.md
      - Schemas: api/schemas.md
      - Fields: api/fields.md
      - Validators: api/validators.md
      - Route: api/route.md
      - Security: api/security.md
      - Helpers: api/helpers.md
      - Commands: api/commands.md
  - مقایسه و انگیزه ها: comparison.md
  - توسعه دهندگان: authors.md
  - تغییرات: changelog.md
  - راهنمای مشارکت: contributing.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            heading_level: 2
      watch:
        - src/apiflask
        - README.md
        - examples/README.md
        - CHANGES.md
        - CONTRIBUTING.md
extra_css:
  - _assets/extra.css
