[build]
  publish = "site"
  command = "pip install -r requirements/docs.txt && pip install flask flask-marshmallow webargs flask-httpauth apispec && pip install . && export PYTHONPATH=$(pwd) && mkdocs build"
